### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by jonasdekeukelaere** [sumocoders/FrameworkMultiUserBundle#34]
by method of "hadAccessTo" in user entities?

**Comment by bjorvack** [comment]
wouldn't symfony voters be more usefull

**Comment by jonasdekeukelaere** [comment]
@sumocoders/php-team Someone still has an idea what this what about?

**Comment by ohvitorino** [comment]
@jonasdekeukelaere Could you give some more context on this issue?

**Comment by ohvitorino** [comment]
@jonasdekeukelaere could you give some more context on this issue?

**Comment by jonasdekeukelaere** [comment]
I don't know anymore haha, it's been open for almost a year ;)
