### ISSUE TITLE
Move base config to the bundle

### ISSUE THREAD

**Issue by StijnVrolijk** [sumocoders/FrameworkMultiUserBundle#37]
Currently we require the user to implement a lot of config stuff in his config.
We could easily move this to the bundle itself.

**Comment by StijnVrolijk** [comment]
not so easily done it appears.. I'm going to leave this open in case someone wants to tackle this

**Comment by jonasdekeukelaere** [comment]
@StijnVrolijk Is this still relevant? As we have a basic implementation of the multi user bundle.

**Comment by StijnVrolijk** [comment]
It is, but not as relevant as it was before. I wouldn't close this
