### ISSUE TITLE
Rename User to BaseUser

### ISSUE THREAD

**Issue by StijnVrolijk** [sumocoders/FrameworkMultiUserBundle#55]
It happens too often that an implementation of the `User` class is simply named `User`. This causes discriminator mapping issues. If we rename `User` to `BaseUser` we can avoid this problem.

**Comment by jonasdekeukelaere** [comment]
@StijnVrolijk maybe DoctrineUser?

**Comment by ohvitorino** [comment]
I think DoctrineUser would bind the entity completely to the platform being used, not a good idea imo.
At this moment, if we need to, we can still move the annotations to an XML file and the entity doesn't have any coupling with the platform.

**Comment by jonasdekeukelaere** [comment]
There is already a DoctrineUserRepository, so to follow that, I think DoctrineUser would be more logical?

**Comment by StijnVrolijk** [comment]
@jonasdekeukelaere the `DoctrineUserRepository` is a Doctrine implementation of the `UserRepository`. If we follow that logic we should have `BaseUser` with no ties to a platform and a `DoctrineUser` which extends the `BaseUser` and expands it with Doctrine logic. Either way, it's a bit on mosquito sifting as we like to say since the chance we'll ever implement another implementation that's not Doctrine is fairly small. imo.

**Comment by jonasdekeukelaere** [comment]
true

**Comment by ohvitorino** [comment]
Well, that's true.

**Comment by carakas** [comment]
I would go with BaseUser but what will that look like in the database ? will you then have a table named BaseUser or DoctrineUser, won't that look a bit strange?

**Comment by StijnVrolijk** [comment]
@carakas Yes, say we rename this user to `BaseUser` and we implement a `User` in our application, there will be 2 tables called `BaseUser` and `User`. Could be a bit confusing

**Comment by jonasdekeukelaere** [comment]
Maybe remove the User with Doctrine annotation in MultiUserBundle and add it in https://github.com/sumocoders/Framework/issues/201 ?

**Comment by StijnVrolijk** [comment]
@jonasdekeukelaere doing this causes the MultiUserBundle to be useless on it's own so I'm not a big fan of it.

**Comment by jonasdekeukelaere** [comment]
Then you'll always have the extra useless table I think

**Comment by carakas** [comment]
@StijnVrolijk Can't we ignore the implementation from theMultiUserBundle and use our own base enity in the Framework? isn't everything typehinted on interfaces?

**Comment by jonasdekeukelaere** [comment]
The problem is that Doctrine will detect the `@Entity` tag and make a table for that entity ;)

**Comment by StijnVrolijk** [comment]
@jonasdekeukelaere it's not useless, it holds the core information a user should have.

**Comment by StijnVrolijk** [comment]
The other alternative is simply leaving it as `User` and properly define an implemented user by naming it `MyProjectUser`. That makes more sense but it just looks stupid in the code (imo)

**Comment by StijnVrolijk** [comment]
@carakas in theory, yes. The only classes that use the actual entity in the MultiUserBundle are it's repositories and DTO and the bundle's tests.

**Comment by carakas** [comment]
You can leave it like it is now and add BaseUser and AdminUser in the framework?

**Comment by StijnVrolijk** [comment]
@carakas that would leave us with 3 tables :p

**Comment by ohvitorino** [comment]
@StijnVrolijk Is there a way to reduce the amount of tables? As far as I know, with the multiuserbundle you'll always need a table to each specific type of user and a table for the user's core information.

**Comment by StijnVrolijk** [comment]
@ohvitorino no way to reduce it afaik...

@sumocoders/php-team so what are we going to do with this?

**Comment by ohvitorino** [comment]
My preference goes to:

MultiUserBundle: 
- BaseUser

Table name will be `BaseUser`

FrameworkCodeBundle:
- User
- Admin

Table names: `User` and `Admin`

We won't be using this BaseUser anywhere else unless as an extension.
So in controllers and views using something like `$user instanceof User` or `$user instanceof Admin` looks much more natural to me.
