### ISSUE TITLE
Implement basic UserBundle in Framework

### ISSUE THREAD

**Issue by jonasdekeukelaere** [sumocoders/FrameworkMultiUserBundle#57]
With Admin and User, maybe wait till https://github.com/sumocoders/FrameworkMultiUserBundle/issues/55 is done, so we don't need to call our User something like FrameworkUser.

**Comment by StijnVrolijk** [comment]
@jonasdekeukelaere shouldn't this issue be in https://github.com/sumocoders/framework ?

**Comment by jonasdekeukelaere** [comment]
Yes my mistake. See https://github.com/sumocoders/Framework/issues/201
