### ISSUE TITLE
Option to change User type

### ISSUE THREAD

**Issue by jonasdekeukelaere** [sumocoders/FrameworkMultiUserBundle#58]
Make it possible to "upgrade"/"downgrade" or just "change" User from user type, like from User to Admin.

**Comment by StijnVrolijk** [comment]
@jonasdekeukelaere this will be very difficult imo because different user types can have wildly different properties.

**Comment by jonasdekeukelaere** [comment]
Yeah, probably will be custom integration I think, but it is something to think about, because it's a bit stupid you can't change it.

**Comment by jonasdekeukelaere** [comment]
And problaby an issue for https://github.com/sumocoders/Framework too I think
